/**
 * Autogenerated by Postman CLI (postman mock generate)
 */
const http = require('http');
const PORT = process.env.PORT || 4500;

const server = http.createServer((req, res) => {
  const url = new URL(req.url || '', 'http://localhost');
  const pathname = url.pathname;

  // @endpoint GET /markets/v1/events
  if (req.method === 'GET' && pathname === '/markets/v1/events') {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"events":[{"event_id":"EVT-FINAL-2026","name":"Championship Final: Harbor Hawks vs. Summit Bears","starts_at":"2026-10-25T00:30:00Z","league":"Sandbox League"}]}));
  }

  // @endpoint GET /markets/v1/markets
  if (req.method === 'GET' && pathname === '/markets/v1/markets') {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"markets":[{"market_id":"MKT-ML-001","event_id":"EVT-FINAL-2026","type":"moneyline","name":"Moneyline","outcomes":[{"outcome_id":"OUT-HAWKS","name":"Harbor Hawks","american_odds":-130,"decimal_odds":1.77},{"outcome_id":"OUT-BEARS","name":"Summit Bears","american_odds":110,"decimal_odds":2.1}]},{"market_id":"MKT-TOT-001","event_id":"EVT-FINAL-2026","type":"total","name":"Total Points 47.5","outcomes":[{"outcome_id":"OUT-OVER","name":"Over 47.5","american_odds":-110,"decimal_odds":1.91},{"outcome_id":"OUT-UNDER","name":"Under 47.5","american_odds":-110,"decimal_odds":1.91}]}]}));
  }

  // @endpoint POST /wallet/v1/wallet/balance
  if (req.method === 'POST' && pathname === '/wallet/v1/wallet/balance') {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"player_id":"P-1001","cash_minor":25000,"bonus_minor":0,"rewards_minor":1200}));
  }

  // @endpoint POST /wallet/v1/wallet/rewards/credit
  if (req.method === 'POST' && pathname === '/wallet/v1/wallet/rewards/credit') {
    res.writeHead(201, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"player_id":"P-1001","rewards_minor":1300,"idempotency_key":"demo-credit-001"}));
  }

  // @endpoint GET /promotions/v1/boosts
  if (req.method === 'GET' && pathname === '/promotions/v1/boosts') {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"boosts":[]}));
  }

  // @endpoint POST /promotions/v1/boosts
  if (req.method === 'POST' && pathname === '/promotions/v1/boosts') {
    res.writeHead(201, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"boost_id":"BST-00001","name":"Championship Rewards Boost","market_id":"MKT-ML-001","profit_boost_pct":25,"rewards_back_pct":10,"products":["sportsbook","casino"],"status":"active","created_at":"2026-10-07T20:02:15.130Z"}));
  }

  // @endpoint POST /promotions/v1/boosts/claim
  if (req.method === 'POST' && pathname === '/promotions/v1/boosts/claim') {
    res.writeHead(201, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"claim_id":"CLM-00002","boost_id":"BST-00001","player_id":"P-1001","claimed_at":"2026-10-07T20:02:15.130Z"}));
  }

  // @endpoint GET /promotions/v1/boosts/claims
  if (req.method === 'GET' && pathname === '/promotions/v1/boosts/claims') {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"claims":[{"claim_id":"CLM-00002","boost_id":"BST-00001","player_id":"P-1001","claimed_at":"2026-10-07T20:02:15.130Z"}]}));
  }

  // @endpoint POST /player-limits/v1/eligibility/check
  if (req.method === 'POST' && pathname === '/player-limits/v1/eligibility/check') {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"player_id":"P-1003","product":"sportsbook","eligible":false,"reasons":["SELF_EXCLUDED"],"may_receive_promotions":false,"remaining_daily_wager_minor":50000,"checked_at":"2026-10-07T20:02:15.131Z"}));
  }

  // @endpoint POST /player-limits/v1/limits
  if (req.method === 'POST' && pathname === '/player-limits/v1/limits') {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"player_id":"P-1002","status":"active","daily_wager_limit_minor":5000,"wagered_today_minor":3000}));
  }

  // @endpoint POST /bets/v1/bets
  if (req.method === 'POST' && pathname === '/bets/v1/bets') {
    res.writeHead(201, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"bet_id":"BET-00003","player_id":"P-1001","status":"accepted","product":"sportsbook","selections":[{"market_id":"MKT-ML-001","outcome_id":"OUT-HAWKS"}],"stake_minor":1000,"potential_payout_minor":1770,"boost_id":null,"rewards_earned_minor":0,"placed_at":"2026-10-07T20:02:15.131Z"}));
  }

  // @endpoint GET /bets/v1/bets
  if (req.method === 'GET' && pathname === '/bets/v1/bets') {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"bets":[{"bet_id":"BET-00003","player_id":"P-1001","status":"accepted","product":"sportsbook","selections":[{"market_id":"MKT-ML-001","outcome_id":"OUT-HAWKS"}],"stake_minor":1000,"potential_payout_minor":1770,"boost_id":null,"rewards_earned_minor":0,"placed_at":"2026-10-07T20:02:15.131Z"}]}));
  }

  // @endpoint POST /geo-compliance/v1/location/check
  if (req.method === 'POST' && pathname === '/geo-compliance/v1/location/check') {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"player_id":"P-1004","state":"NY","product":"casino","allowed":false,"reason":"PRODUCT_NOT_AVAILABLE_IN_STATE"}));
  }

  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ error: 'Endpoint not defined' }));
});

server.listen(PORT);
